build:
  distributions:
    ubuntu:
      - bionic # 18.04
      - focal  # 20.04
      - jammy  # 22.04
      - noble  # 24.04
    debian:
      - buster # 10
      - bullseye # 11
      - bookworm # 12
  versions:
    - v2.2.0
    - v2.2.1
    - v2.2.2
    - v2.2.3
    - v2.2.4
    - v2.2.5
    - v2.3.0-beta1
    - v2.2.6
    - v2.3.0-beta2
    - master
