name: scheduled build
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - bionic
          - focal
          - jammy
          - noble
          - bullseye
          - bookworm
          - trixie
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          ruby-version: 3.0
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        id: meta
        with:
          images: ghcr.io/unasuke/h2o-docker
          tags: |
            type=raw,value=${{ matrix.distribution }}-master
      - run: ./gen_dockerfile.rb '${{ matrix.distribution }}' master
      - uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          push: true
          file: Dockerfile.${{ matrix.distribution }}_master
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  test:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - bionic
          - focal
          - jammy
          - noble
          - bullseye
          - bookworm
          - trixie
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker run --detach --volume $(pwd)/test:/etc --publish 8080:8080 --stop-timeout 15 'ghcr.io/unasuke/h2o-docker:${{ matrix.distribution }}-master' h2o -c /etc/h2o.conf
          sleep 3
          curl  http://localhost:8080 | grep 'Hello world'
