
name: scheduled build
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - bionic
          - focal
          - jammy
          - buster
          - bullseye
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/unasuke/h2o-docker
          tags: |
            type=raw,value=${{ matrix.distribution }}-master
      - run: ./gen_dockerfile.rb '${{ matrix.distribution }}' master
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          no-cache: true
          file: Dockerfile.${{ matrix.distribution }}_master
          tags: ${{ steps.meta.outputs.tags }}
  test:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - bionic
          - focal
          - jammy
          - buster
          - bullseye
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker run --detach --volume $(pwd)/test:/etc --publish 8080:8080 --stop-timeout 15 'ghcr.io/unasuke/h2o-docker:${{ matrix.distribution }}-master' h2o -c /etc/h2o.conf
          sleep 3
          curl  http://localhost:8080 | grep 'Hello world'
